### ISSUE TITLE
JGroups cluster manager in production

### ISSUE THREAD

**Issue by SergeyMagid** [vert-x3/vertx-jgroups#11]
Is somebody use this cluster manager implementation in production?

**Comment by cescoffier** [comment]
You should ask on the google group (and not as an issue)

On 24 sept. 2015, at 16:30, smagid notifications@github.com wrote:

Is somebody use this cluster manager implementation in production?

—
Reply to this email directly or view it on GitHub
https://github.com/vert-x3/vertx-jgroups/issues/11.
