### ISSUE TITLE
ClusterWideMap callbacks are executed on wrong threads.

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-jgroups#15]
I noticed that disableThreadChecks() is being called on all JGroups clustering tests (these should all be removed).

Checking threads is very important in Vert.x tests to ensure that callbacks are executed on the correct thread.

That thread should always be the exact same event loop if the operation was called from an event loop, or a worker thread with the same context. If that's not followed the Vert.x threading model is broken.

To ensure this happens, blocking operations can be called using vertx.executeBlocking, or async callbacks can be executed on the correct thread using context.runOnContext().

If the disableThreadChecks() line is removed, from, e.g., JGroupsClusterWideMapTest many tests fail.

**Comment by cescoffier** [comment]
Fixed in https://github.com/vert-x3/vertx-jgroups/pull/16.
