### ISSUE TITLE
Move implementation packages in an `impl` package

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-jgroups#21]
For example:

`io.vertx.spi.cluster.jgroups.domain` => `io.vertx.spi.cluster.jgroups.impl.domain`

So, the implementation won't be in the public javadoc.

**Comment by cescoffier** [comment]
As it's just implementation packages, it's not a breaking change.

**Comment by fmarinelli** [comment]
PR https://github.com/vert-x3/vertx-jgroups/pull/22

**Comment by cescoffier** [comment]
Fixed in #22
