### ISSUE TITLE
Create some documentation

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-jgroups#3]
We should have some basic docs and a README for this component.

Something similar to the docs that I recently added to the vertx-hazelcast project in this commit https://github.com/vert-x3/vertx-hazelcast/pull/8

@fmarinelli

**Comment by purplefox** [comment]
Hi Fabio - any news on this?

**Comment by purplefox** [comment]
@fmarinelli Documentation in Vert.x is generated from package-info.java files - we don't edit the adoc directly.

Can you take a look at the Hazelcast as an example?

**Comment by cescoffier** [comment]
I've refactored the documentation to follow the generation process we used in other vert.x project - see https://github.com/vert-x3/vertx-jgroups/pull/8
